# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\Program Files (x86)\chrome_driver\\chromedriver.exe')

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("http://192.168.0.75:50000/main/upload")
    self.driver.set_window_size(1600, 893)
    self.driver.find_element(By.CSS_SELECTOR, ".upload-inner").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("C:\\fakepath\\.When_the_Hammer_Falls_-_Clamavi_De_Profundis_(Original_Song)_by_None.zip")
    self.driver.find_element(By.CSS_SELECTOR, ".toast-message").click()
  
